---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/k3s -v
      register: k3s_test_output
    - name: k3s -v
      debug:
        msg: '{{ k3s_test_output.stdout }}'
