---
- name: Testing andrewrothstein.k3s
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'k3s -v'
      ansible.builtin.command: /usr/local/bin/k3s -v
      changed_when: false
      register: k3s_test_output
    - name: Output from 'k3s -v'
      ansible.builtin.debug:
        msg: '{{ k3s_test_output.stdout }}'
